version: '3'

services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: api-server
    ports:
      - "5000:3000"
    volumes:
      - ./server/src:/app
  reactapp:
  
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "5001:3000"
    volumes:
      - ./client/src:/App