version: '3'

services:
#################
  unpazforms-api:
    build:
      context: ./server/src
      dockerfile: Dockerfile
    container_name: unpazforms-api
    ports:
      - "5001:8080"
    #volumes:
    # - ./server/src:/app
    networks:
      - app_unpazforms
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
####################
  unpazforms-frontend-web:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: unpazforms-frontend-web
    ports:
      - "5000:3000"
    #volumes:
      #- ./client/src:/app
    networks:
      - app_unpazforms
######################
  unpazforms_bd:
    image: postgres:14.5-bullseye
    container_name: unpazforms_bd
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - ./extra/BD_01_DDL.sql:/docker-entrypoint-initdb.d/BD_01_DDL.sql
      - volumen_bd_unpazforms:/var/lib/postgresql/data
    networks:
      - app_unpazforms
#####################
  unpazforms-tool-pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=bd@bd.com
      - PGADMIN_DEFAULT_PASSWORD=test123!
    ports:
      - "6001:80"
    volumes:
      - volumen_pgadmin_data:/var/lib/pgadmin
    networks:
      - app_unpazforms
###################
networks:
  app_unpazforms:
    name: network_app_unpazforms
####################
volumes:
  volumen_bd_unpazforms:
  volumen_pgadmin_data: